name: Smart Irrigation Controller
version: "1.0.6"
slug: smart_irrigation
description: Automated irrigation system with weather intelligence and Z2M valve control
url: https://github.com/ttaylor0024/HA_Z2M_Smart_Irrigation
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64:   "ghcr.io/home-assistant/amd64-base:3.18"
  armhf:   "ghcr.io/home-assistant/armhf-base:3.18"
  armv7:   "ghcr.io/home-assistant/armv7-base:3.18"
  i386:    "ghcr.io/home-assistant/i386-base:3.18"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
ingress: true
ingress_port: 8080
panel_icon: mdi:sprinkler
panel_title: Smart Irrigation
startup: services
boot: auto
options:
  weather_api_key: ""
  weather_provider: "openweathermap"
  latitude: 0.0
  longitude: 0.0
  units: "metric"
  zones:
    - name: "Zone 1"
      entity_id: ""
      enabled: true
      zone_type: "lawn"
      duration: 15
      schedule: "06:00"
      days: ["mon", "wed", "fri"]
      flow_sensor: ""
      moisture_sensor: ""
      moisture_threshold: 30
  rain_forecast:
    enabled: true
    threshold_mm: 5.0
    hours_ahead: 24
    skip_percentage: 70
  recent_rain:
    enabled: true
    threshold_mm: 10.0
    hours_back: 24
    compensation_enabled: true
    compensation_ratio: 0.5
  soil_moisture:
    enabled: false
    default_threshold: 30
  advanced:
    between_zone_delay: 30
    test_mode_duration: 1
    flow_rate_assumption: 10
    enable_statistics: true
schema:
  weather_api_key: str
  weather_provider: list(openweathermap|weatherapi|visualcrossing)
  latitude: float
  longitude: float
  units: list(metric|imperial)
  zones:
    - name: str
      entity_id: str
      enabled: bool
      zone_type: list(lawn|garden|drip|flowers|trees)
      duration: int(1,120)
      schedule: match(^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$)
      days: 
        - list(mon|tue|wed|thu|fri|sat|sun)
      flow_sensor: str?
      moisture_sensor: str?
      moisture_threshold: int
  rain_forecast:
    enabled: bool
    threshold_mm: float
    hours_ahead: int
    skip_percentage: int
  recent_rain:
    enabled: bool
    threshold_mm: float
    hours_back: int
    compensation_enabled: bool
    compensation_ratio: float
  soil_moisture:
    enabled: bool
    default_threshold: int
  advanced:
    between_zone_delay: int
    test_mode_duration: int
    flow_rate_assumption: float
    enable_statistics: bool
ports:
  8080/tcp: null
ports_description:
  8080/tcp: "Web interface"
webui: http://[HOST]:[PORT:8080]
map:
  - config:ro
host_network: false
